.TH permute 1 permute\-0.0.1
.SH NAME
permute \- show permutations or combinations of lists
.SH SYNOPSIS
.B permute [OPTIONS] FILE
.SH DESCRIPTION
.B permute
takes a file or standard in, 
treats each line as a comma-delimited list,
and outputs all permutations of that list,
one permutation per output line.
Optionally, 
the output lists can be limited in length.
.SH OPTIONS
.LP
.B -p 
output permutations. This is the default.
.LP
.B -c 
output combinations rather than permutations \(em That is,
order of elements in the resulting lists is not important.
.LP
.B -rp 
output repeated permutations \(em That is,
allow output elements to be repeated.
.LP
.B -rc 
output repeated combinations \(em That is,
order of elements in the resulting lists is not important, 
and output elements may be repeated.
.LP
.B -n NUMBER
limit length of output lists to NUMBER.
.LP
.B -d DELIMITER
use DELIMITER rather than `,' to separate items of list.
.SH EXAMPLES
.LP
What are my options for doing some chores?
.LP
.B echo 'make dinner,clean living room,change light bulb' | permute
.LP
What kind of two topping pizzas can I order?
.LP
.B echo 'sausage,pepperoni,mushroom,olive' | permute -n 2 -c 
.LP
A preliminary investigation of the children's game Cherry-Oh
.LP
.B echo 'n+=1,n+=2,n+=3,n+=4,n=0,n=(n<3 ? 0 : n-2),n=(n<3 ? 0 : n-2)' |\
 permute -rp -n 8
.SH SEE ALSO
.B ruby(1), ri permutation, ri combination, ri repeated_permutation,
.B ri repeated_combination
.LP
http://mathworld.wolfram.com/Permutation.html
.SH BUGS
Order of output is not guaranteed.
(This is probably a feature, not a bug.)
Probably others.
.SH LICENSE
Copyright 2013 
.sp
You may use this software however you like.
