#!/usr/bin/env ruby

def usage(s)
    $stderr.puts(s)
    $stderr.puts("Usage: #{File.basename($0)}: [OPTIONS] file ...")
    exit(2)
end

i = 0
$delim = ","
$operation = "permutation"

loop { case ARGV[0]
    when '-p'  then ARGV.shift; $operation = "permutation"
    when '-c'  then ARGV.shift; $operation = "combination"
    when '-rp' then ARGV.shift; $operation = "repeated_permutation"
    when '-rc' then ARGV.shift; $operation = "repeated_combination"
    when '-n'  then ARGV.shift; $numperm = ARGV.shift.to_i
    when '-d'  then ARGV.shift; $delim = ARGV.shift
    when /--/  then ARGV.shift; break
    when /^-/  then usage("Unknown option: #{ARGV[0].inspect}")
    else break
end; }

list = Array.new

while gets() do
    line = $_.chomp
    list = line.split($delim)
    if defined? $numperm
        if ($numperm > list.length) && ($operation !~ /repeated/)
            warn "#{$numperm} greater than number of elements"
        end
    else
        $numperm = list.length
    end

    method = list.method("#{$operation}")
    method.call($numperm).to_a.each do |a|
        puts a.join($delim)
    end
end
